name: "Build Non-Windows images"
# author: Carl Wilson <carl_AT_openpreservation.org>

on:
  workflow_call:
    inputs:
      release_version:
        description: "Release version"
        required: true
        type: string
      release_tag:
        description: "Release tag"
        required: true
        type: string
jobs:
  build:
    name: "Build Non-Windows image"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: 'ubuntu-latest'
            label: 'linux'
          - os: 'macos-latest'
            label: 'mac'
    runs-on: ${{matrix.os}}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Setup Java 11'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11

    - name: 'Setup GraalVM Environment'
      uses: DeLaGuardo/setup-graalvm@5.0
      with:
        graalvm: "20.0.0.2"
        java: "java11"
        arch: "amd64"

    - name: 'Install Native Image Plugin'
      run: |
        gu.cmd install native-image

    - name: 'Get JAR Artifact'
      uses: actions/download-artifact@v4
      with:
        name: 'odf-validator-${{ github.event.inputs.release_version }}-all.jar'

    - name: 'Build Native Image'
      run: |
        native-image --no-server --no-fallback -H:ReflectionConfigurationResources=reflection-config.json -H:IncludeResources=logback.xml --allow-incomplete-classpath -jar odf-validator-${{ github.event.inputs.release_version }}-all.jar

    - name: 'Publish Native Image'
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: 'odf-validator-${{ github.event.inputs.release_version }}-${{matrix.label}}'
        path: 'odf-validator-${{ github.event.inputs.release_version }}-all'

    - name: "Upload release binaries"
      if: success()
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "odf-validator-${{ github.event.inputs.release_version }}-all"
        asset_name: "odf-validator-${{ github.event.inputs.release_version }}-${{matrix.label}}"
        tag: "${{ github.event.inputs.release_tag }}"
        overwrite: true
        draft: false
        prerelease: false
